'use client'

import { useEffect, useState, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/hooks/useAuth'
import { profileCache } from '@/lib/cache/profile-cache'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import Card from '@/components/ui/Card'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import Modal from '@/components/ui/Modal'
import { formatDate, formatDateTime } from '@/lib/utils/date-helpers'
import toast from 'react-hot-toast'


export default function SessionsPage() {
  const router = useRouter()
  const { user, profile, loading: authLoading } = useAuth()
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [showQRModal, setShowQRModal] = useState(false)
  const [selectedSession, setSelectedSession] = useState(null)
  const [saving, setSaving] = useState(false)
  
  const [sessionForm, setSessionForm] = useState({
    session_date: '',
    start_time: '',
    end_time: '',
    squad: '',
    pool_location: '',
  })

  useEffect(() => {
    // Optimistic auth check - use cached profile if available
    const cachedProfile = user ? profileCache.get(user.id) : null
    
    if (!authLoading) {
      if (!user || (profile?.role !== 'admin' && cachedProfile?.role !== 'admin')) {
        router.push('/login')
        return
      }
    }
    
    // Load data immediately if we have user (even if profile still loading)
    if (user && !sessions.length) {
      loadSessions()
    }
  }, [user, profile, authLoading])

  async function loadSessions() {
    const supabase = createClient()
    setLoading(true)

    try {
      const { data, error } = await supabase
        .from('training_sessions')
        .select('*')
        .order('session_date', { ascending: false })
        .order('start_time', { ascending: false })
        .limit(50)

      if (error) throw error
      setSessions(data || [])
    } catch (error) {
      console.error('Error loading sessions:', error)
      toast.error('Failed to load sessions')
    } finally {
      setLoading(false)
    }
  }

  async function handleCreateSession() {
    if (!sessionForm.session_date || !sessionForm.start_time || !sessionForm.end_time || !sessionForm.squad || !sessionForm.pool_location) {
      toast.error('Please fill in all required fields')
      return
    }

    setSaving(true)
    const supabase = createClient()

    try {
      const { data, error } = await supabase
        .from('training_sessions')
        .insert({
          session_date: sessionForm.session_date,
          start_time: sessionForm.start_time,
          end_time: sessionForm.end_time,
          squad: sessionForm.squad,
          pool_location: sessionForm.pool_location,
          coach_id: user.id,
          // qr_code_token is auto-generated by database
        })
        .select()
        .single()

      if (error) throw error

      toast.success('Training session created successfully')
      setShowCreateModal(false)
      setSessionForm({
        session_date: '',
        start_time: '',
        end_time: '',
        squad: '',
        pool_location: '',
      })
      loadSessions()
    } catch (error) {
      console.error('Error creating session:', error)
      toast.error('Failed to create session')
    } finally {
      setSaving(false)
    }
  }

  const showQRCode = useCallback(async (session) => {
    setSelectedSession(session)
    setShowQRModal(true)
  }, [])

  async function handleDeleteSession(session) {
    if (!confirm(`Delete session on ${formatDate(session.session_date)}?`)) {
      return
    }

    const supabase = createClient()

    try {
      const { error} = await supabase
        .from('training_sessions')
        .delete()
        .eq('id', session.id)

      if (error) throw error

      toast.success('Session deleted')
      loadSessions()
    } catch (error) {
      console.error('Error deleting session:', error)
      toast.error('Failed to delete session')
    }
  }

  function downloadQRCode() {
    const link = document.createElement('a')
    link.download = `session-qr-${selectedSession.id}.png`
    link.href = qrCodeUrl
    link.click()
  }

  function printQRCode() {
    const printWindow = window.open('', '', 'width=800,height=600')
    printWindow.document.write(`
      <html>
        <head>
          <title>Session Code - ${selectedSession.qr_code_token}</title>
          <style>
            body { 
              font-family: 'Arial', sans-serif; 
              text-align: center; 
              padding: 40px;
              margin: 0;
            }
            .header {
              margin-bottom: 40px;
            }
            .code-box {
              background: linear-gradient(135deg, #0084d5 0%, #0066aa 100%);
              color: white;
              padding: 80px 60px;
              border-radius: 20px;
              margin: 40px 0;
              box-shadow: 0 10px 40px rgba(0,132,213,0.3);
            }
            .code-label {
              font-size: 20px;
              text-transform: uppercase;
              letter-spacing: 3px;
              opacity: 0.9;
              margin-bottom: 20px;
            }
            .code {
              font-size: 120px;
              font-weight: bold;
              letter-spacing: 18px;
              margin: 30px 0;
              font-family: 'Courier New', monospace;
              text-shadow: 0 2px 10px rgba(0,0,0,0.2);
            }
            .session-info {
              font-size: 22px;
              margin-top: 30px;
              padding-top: 30px;
              border-top: 2px solid rgba(255,255,255,0.3);
              opacity: 0.95;
            }
            .instructions {
              background: #f0f9ff;
              padding: 30px;
              border-radius: 15px;
              margin-top: 40px;
              text-align: left;
            }
            .instructions h3 {
              color: #0084d5;
              margin-bottom: 15px;
              font-size: 20px;
            }
            .instructions ol {
              font-size: 16px;
              line-height: 2;
              color: #334155;
            }
            @media print {
              body { padding: 20px; }
              .code-box { page-break-inside: avoid; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 style="color: #0084d5; font-size: 32px; margin: 0;">OTTERS KENYA SWIM CLUB</h1>
            <p style="font-size: 18px; color: #64748b; margin-top: 5px;">Training Session Check-In</p>
          </div>
          
          <div class="code-box">
            <div class="code-label">Session Code</div>
            <div class="code">${selectedSession.qr_code_token}</div>
            <div class="session-info">
              <p style="margin: 5px 0;">${formatDate(selectedSession.session_date)}</p>
              <p style="margin: 5px 0;">${selectedSession.start_time} - ${selectedSession.end_time}</p>
              <p style="margin: 5px 0;">${selectedSession.squad.replace('_', ' ').toUpperCase()} • ${selectedSession.pool_location}</p>
            </div>
          </div>
          
          <div class="instructions">
            <h3>🏊 Parent Check-In Steps:</h3>
            <ol>
              <li>Open the Otters Kenya app on your phone</li>
              <li>Tap "Check-In" from the menu</li>
              <li>Select which swimmer is present</li>
              <li>Enter the code: <strong>${selectedSession.qr_code_token}</strong></li>
              <li>Tap "Check In" button</li>
              <li>Done! ✅ Check-in is recorded</li>
            </ol>
          </div>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (authLoading || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
      </div>
    )
  }

  return (
    <>
      <Navigation />
      
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-8 flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Training Sessions</h1>
              <p className="text-gray-600 mt-2">Manage pool schedule and generate check-in codes</p>
            </div>
            <Button onClick={() => setShowCreateModal(true)}>
              + Create Session
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-4">
            {sessions.length === 0 ? (
              <Card>
                <div className="text-center py-12">
                  <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <h3 className="mt-2 text-sm font-medium text-gray-900">No sessions scheduled</h3>
                  <p className="mt-1 text-sm text-gray-500">Get started by creating a training session.</p>
                </div>
              </Card>
            ) : (
              sessions.map((session) => (
                <Card key={session.id} padding="normal">
                  <div className="flex justify-between items-start">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="text-lg font-semibold text-gray-900">
                          {formatDate(session.session_date)}
                        </h3>
                        <span className="px-3 py-1 bg-primary text-white text-sm rounded-full">
                          {session.squad.replace('_', ' ').toUpperCase()}
                        </span>
                      </div>
                      <div className="space-y-1 text-sm text-gray-600">
                        <p>⏰ {session.start_time} - {session.end_time}</p>
                        <p>📍 {session.pool_location}</p>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="secondary"
                        onClick={() => showQRCode(session)}
                      >
                        View Check-In Code
                      </Button>
                      <Button
                        size="sm"
                        variant="danger"
                        onClick={() => handleDeleteSession(session)}
                      >
                        Delete
                      </Button>
                    </div>
                  </div>
                </Card>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Create Session Modal */}
      <Modal
        isOpen={showCreateModal}
        onClose={() => setShowCreateModal(false)}
        title="Create Training Session"
        size="lg"
        footer={
          <div className="flex gap-3 justify-end">
            <Button
              variant="secondary"
              onClick={() => setShowCreateModal(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateSession}
              loading={saving}
            >
              Create Session
            </Button>
          </div>
        }
      >
        <div className="grid grid-cols-2 gap-4">
          <Input
            label="Session Date"
            type="date"
            required
            value={sessionForm.session_date}
            onChange={(e) => setSessionForm({ ...sessionForm, session_date: e.target.value })}
          />
          <div className="grid grid-cols-2 gap-2">
            <Input
              label="Start Time"
              type="time"
              required
              value={sessionForm.start_time}
              onChange={(e) => setSessionForm({ ...sessionForm, start_time: e.target.value })}
            />
            <Input
              label="End Time"
              type="time"
              required
              value={sessionForm.end_time}
              onChange={(e) => setSessionForm({ ...sessionForm, end_time: e.target.value })}
            />
          </div>
          <Select
            label="Squad"
            required
            value={sessionForm.squad}
            onChange={(e) => setSessionForm({ ...sessionForm, squad: e.target.value })}
            options={[
              { value: 'competitive', label: 'Competitive' },
              { value: 'learn_to_swim', label: 'Learn to Swim' },
              { value: 'fitness', label: 'Fitness' },
            ]}
          />
          <Input
            label="Pool Location"
            required
            value={sessionForm.pool_location}
            onChange={(e) => setSessionForm({ ...sessionForm, pool_location: e.target.value })}
            placeholder="e.g., Main Pool, Training Pool"
          />
        </div>
      </Modal>

      {/* Session Code Modal */}
      <Modal
        isOpen={showQRModal}
        onClose={() => setShowQRModal(false)}
        title="Session Check-In Code"
        size="lg"
      >
        {selectedSession && (
          <div className="space-y-6">
            {/* Big Code Display */}
            <div className="bg-gradient-to-br from-primary to-primary-dark rounded-2xl p-10 shadow-2xl text-center">
              <p className="text-white/80 text-sm font-medium mb-3 uppercase tracking-wide">Session Code</p>
              <p className="text-white text-6xl md:text-7xl font-bold tracking-widest font-mono mb-6">
                {selectedSession.qr_code_token}
              </p>
              <div className="pt-4 border-t border-white/20">
                <p className="text-white text-lg font-medium">{formatDate(selectedSession.session_date)}</p>
                <p className="text-white/90 text-sm mt-2">
                  {selectedSession.start_time} - {selectedSession.end_time}
                </p>
                <p className="text-white/80 text-sm mt-1">
                  {selectedSession.squad.replace('_', ' ').toUpperCase()} • {selectedSession.pool_location}
                </p>
              </div>
            </div>

            {/* Instructions */}
            <div className="bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-800 rounded-xl p-5">
              <div className="flex items-start mb-3">
                <svg className="w-6 h-6 text-blue-600 dark:text-blue-400 mr-3 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd"/>
                </svg>
                <div>
                  <h4 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">Parent Check-In Instructions</h4>
                  <ol className="text-sm text-blue-800 dark:text-blue-200 space-y-2">
                    <li><strong>1. Display this code</strong> at the poolside (print or show on screen)</li>
                    <li><strong>2. Parents open</strong> the check-in page on their phone/device</li>
                    <li><strong>3. They select</strong> which swimmer is present</li>
                    <li><strong>4. They enter</strong> the code shown above</li>
                    <li><strong>5. Check-in recorded</strong> instantly with timestamp</li>
                  </ol>
                </div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="grid grid-cols-2 gap-3">
              <Button
                variant="secondary"
                fullWidth
                onClick={() => {
                  navigator.clipboard.writeText(selectedSession.qr_code_token)
                  toast.success('Code copied to clipboard!')
                }}
              >
                📋 Copy Code
              </Button>
              <Button
                variant="primary"
                fullWidth
                onClick={printQRCode}
              >
                🖨️ Print Code
              </Button>
            </div>
          </div>
        )}
      </Modal>

      <Footer />
    </>
  )
}
