'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { useAuth } from '@/hooks/useAuth'
import Navigation from '@/components/Navigation'
import Footer from '@/components/Footer'
import Card from '@/components/ui/Card'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import Modal from '@/components/ui/Modal'
import { formatDate, formatDateTime } from '@/lib/utils/date-helpers'
import toast from 'react-hot-toast'
import QRCode from 'qrcode'

export default function SessionsPage() {
  const router = useRouter()
  const { user, profile, loading: authLoading } = useAuth()
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [showQRModal, setShowQRModal] = useState(false)
  const [selectedSession, setSelectedSession] = useState(null)
  const [qrCodeUrl, setQrCodeUrl] = useState('')
  const [saving, setSaving] = useState(false)
  
  const [sessionForm, setSessionForm] = useState({
    session_date: '',
    start_time: '',
    end_time: '',
    squad: '',
    pool_location: '',
  })

  useEffect(() => {
    if (!authLoading) {
      if (!user || profile?.role !== 'admin') {
        router.push('/login')
        return
      }
      loadSessions()
    }
  }, [user, profile, authLoading, router])

  async function loadSessions() {
    const supabase = createClient()
    setLoading(true)

    try {
      const { data, error } = await supabase
        .from('training_sessions')
        .select('*')
        .order('session_date', { ascending: false })
        .order('start_time', { ascending: false })
        .limit(50)

      if (error) throw error
      setSessions(data || [])
    } catch (error) {
      console.error('Error loading sessions:', error)
      toast.error('Failed to load sessions')
    } finally {
      setLoading(false)
    }
  }

  async function handleCreateSession() {
    if (!sessionForm.session_date || !sessionForm.start_time || !sessionForm.end_time || !sessionForm.squad || !sessionForm.pool_location) {
      toast.error('Please fill in all required fields')
      return
    }

    setSaving(true)
    const supabase = createClient()

    try {
      const { data, error } = await supabase
        .from('training_sessions')
        .insert({
          session_date: sessionForm.session_date,
          start_time: sessionForm.start_time,
          end_time: sessionForm.end_time,
          squad: sessionForm.squad,
          pool_location: sessionForm.pool_location,
          coach_id: user.id,
          // qr_code_token is auto-generated by database
        })
        .select()
        .single()

      if (error) throw error

      toast.success('Training session created successfully')
      setShowCreateModal(false)
      setSessionForm({
        session_date: '',
        start_time: '',
        end_time: '',
        squad: '',
        pool_location: '',
      })
      loadSessions()
    } catch (error) {
      console.error('Error creating session:', error)
      toast.error('Failed to create session')
    } finally {
      setSaving(false)
    }
  }

  async function showQRCode(session) {
    setSelectedSession(session)
    
    // Generate QR code URL
    const qrData = JSON.stringify({
      sessionId: session.id,
      token: session.qr_code_token,
      date: session.session_date,
      squad: session.squad,
    })

    try {
      const url = await QRCode.toDataURL(qrData, {
        width: 300,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#FFFFFF',
        },
      })
      setQrCodeUrl(url)
      setShowQRModal(true)
    } catch (error) {
      console.error('Error generating QR code:', error)
      toast.error('Failed to generate QR code')
    }
  }

  async function handleDeleteSession(session) {
    if (!confirm(`Delete session on ${formatDate(session.session_date)}?`)) {
      return
    }

    const supabase = createClient()

    try {
      const { error} = await supabase
        .from('training_sessions')
        .delete()
        .eq('id', session.id)

      if (error) throw error

      toast.success('Session deleted')
      loadSessions()
    } catch (error) {
      console.error('Error deleting session:', error)
      toast.error('Failed to delete session')
    }
  }

  function downloadQRCode() {
    const link = document.createElement('a')
    link.download = `session-qr-${selectedSession.id}.png`
    link.href = qrCodeUrl
    link.click()
  }

  function printQRCode() {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>Training Session QR Code</title>
          <style>
            body {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              min-height: 100vh;
              font-family: sans-serif;
              text-align: center;
            }
            h1 { font-size: 24px; margin-bottom: 10px; }
            p { margin: 5px 0; color: #666; }
            img { margin: 20px 0; }
          </style>
        </head>
        <body>
          <h1>Otters Kenya Training Session</h1>
          <p>${formatDate(selectedSession.session_date)}</p>
          <p>${selectedSession.start_time} - ${selectedSession.end_time}</p>
          <p>${selectedSession.squad.replace('_', ' ').toUpperCase()} - ${selectedSession.pool_location}</p>
          <img src="${qrCodeUrl}" alt="QR Code" />
          <p>Scan to check in</p>
        </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.print()
  }

  if (authLoading || loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
      </div>
    )
  }

  return (
    <>
      <Navigation />
      
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-8 flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Training Sessions</h1>
              <p className="text-gray-600 mt-2">Manage pool schedule and generate QR codes</p>
            </div>
            <Button onClick={() => setShowCreateModal(true)}>
              + Create Session
            </Button>
          </div>

          <div className="grid grid-cols-1 gap-4">
            {sessions.length === 0 ? (
              <Card>
                <div className="text-center py-12">
                  <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  <h3 className="mt-2 text-sm font-medium text-gray-900">No sessions scheduled</h3>
                  <p className="mt-1 text-sm text-gray-500">Get started by creating a training session.</p>
                </div>
              </Card>
            ) : (
              sessions.map((session) => (
                <Card key={session.id} padding="normal">
                  <div className="flex justify-between items-start">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="text-lg font-semibold text-gray-900">
                          {formatDate(session.session_date)}
                        </h3>
                        <span className="px-3 py-1 bg-primary text-white text-sm rounded-full">
                          {session.squad.replace('_', ' ').toUpperCase()}
                        </span>
                      </div>
                      <div className="space-y-1 text-sm text-gray-600">
                        <p>⏰ {session.start_time} - {session.end_time}</p>
                        <p>📍 {session.pool_location}</p>
                      </div>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="secondary"
                        onClick={() => showQRCode(session)}
                      >
                        Show QR Code
                      </Button>
                      <Button
                        size="sm"
                        variant="danger"
                        onClick={() => handleDeleteSession(session)}
                      >
                        Delete
                      </Button>
                    </div>
                  </div>
                </Card>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Create Session Modal */}
      <Modal
        isOpen={showCreateModal}
        onClose={() => setShowCreateModal(false)}
        title="Create Training Session"
        size="lg"
        footer={
          <div className="flex gap-3 justify-end">
            <Button
              variant="secondary"
              onClick={() => setShowCreateModal(false)}
              disabled={saving}
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreateSession}
              loading={saving}
            >
              Create Session
            </Button>
          </div>
        }
      >
        <div className="grid grid-cols-2 gap-4">
          <Input
            label="Session Date"
            type="date"
            required
            value={sessionForm.session_date}
            onChange={(e) => setSessionForm({ ...sessionForm, session_date: e.target.value })}
          />
          <div className="grid grid-cols-2 gap-2">
            <Input
              label="Start Time"
              type="time"
              required
              value={sessionForm.start_time}
              onChange={(e) => setSessionForm({ ...sessionForm, start_time: e.target.value })}
            />
            <Input
              label="End Time"
              type="time"
              required
              value={sessionForm.end_time}
              onChange={(e) => setSessionForm({ ...sessionForm, end_time: e.target.value })}
            />
          </div>
          <Select
            label="Squad"
            required
            value={sessionForm.squad}
            onChange={(e) => setSessionForm({ ...sessionForm, squad: e.target.value })}
            options={[
              { value: 'competitive', label: 'Competitive' },
              { value: 'learn_to_swim', label: 'Learn to Swim' },
              { value: 'fitness', label: 'Fitness' },
            ]}
          />
          <Input
            label="Pool Location"
            required
            value={sessionForm.pool_location}
            onChange={(e) => setSessionForm({ ...sessionForm, pool_location: e.target.value })}
            placeholder="e.g., Main Pool, Training Pool"
          />
        </div>
      </Modal>

      {/* QR Code Modal */}
      <Modal
        isOpen={showQRModal}
        onClose={() => setShowQRModal(false)}
        title="Session QR Code"
        size="md"
        footer={
          <div className="flex gap-3 justify-end">
            <Button variant="secondary" onClick={downloadQRCode}>
              Download
            </Button>
            <Button onClick={printQRCode}>
              Print
            </Button>
          </div>
        }
      >
        {selectedSession && (
          <div className="text-center">
            <h3 className="text-lg font-semibold mb-2">
              {formatDate(selectedSession.session_date)}
            </h3>
            <p className="text-sm text-gray-600 mb-4">
              {selectedSession.start_time} - {selectedSession.end_time}<br />
              {selectedSession.squad.replace('_', ' ').toUpperCase()} - {selectedSession.pool_location}
            </p>
            {qrCodeUrl && (
              <img 
                src={qrCodeUrl} 
                alt="QR Code" 
                className="mx-auto border-4 border-gray-200 rounded-lg"
              />
            )}
            <p className="text-sm text-gray-500 mt-4">
              Swimmers scan this code to check in
            </p>
          </div>
        )}
      </Modal>

      <Footer />
    </>
  )
}
